package assets

import "embed"

// ui contains the built SvelteKit static SPA.
// Generated by `pnpm run build` in ../ui before `go build`.
//
//go:embed all:ui
var ui embed.FS

// icons contains PNGs from selfhst/dashboard-icons.
// Generated by `pnpm icons` in ../ui before `go build`.
//
//go:embed all:icons
var icons embed.FS

// UI returns the embedded UI filesystem rooted at the build output.
func UI() embed.FS { return ui }

// Icons returns the embedded icon filesystem rooted at the icons dir.
func Icons() embed.FS { return icons }
