# Variables
go           := "go"
ui_dir       := "ui"
icons_commit := env_var_or_default("ICONS_COMMIT", "main")
image        := env_var_or_default("IMAGE", "ghcr.io/tekulvw/k8s-auto-dash")
tag          := env_var_or_default("TAG", "dev")
platforms    := env_var_or_default("PLATFORMS", "linux/amd64,linux/arm64")

controller_gen  := "go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.21.0"
envtest_k8s_ver := env_var_or_default("ENVTEST_K8S_VERSION", "1.33.x")
envtest         := "go run sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.24.1"

# Default: list all recipes
default:
	@just --list

# Generate CRD manifests and DeepCopy methods
generate:
	{{controller_gen}} object:headerFile=hack/boilerplate.go.txt paths=./api/...
	{{controller_gen}} crd paths=./api/... output:crd:dir=deploy/crd

# Build the UI and copy artifacts into embed dirs
ui-build:
	cd {{ui_dir}} && pnpm install && ICONS_COMMIT={{icons_commit}} pnpm icons && pnpm run build
	rm -rf internal/assets/ui/* internal/assets/icons/*
	cp -r {{ui_dir}}/build/. internal/assets/ui/
	cp -r {{ui_dir}}/icons/. internal/assets/icons/

# Build UI then Go binary
build-all: ui-build build

# Download envtest binaries for the target k8s version
envtest-assets:
	@{{envtest}} use {{envtest_k8s_ver}} -p path > /dev/null

# Run Go tests (requires envtest assets)
test: envtest-assets
	KUBEBUILDER_ASSETS="$({{envtest}} use {{envtest_k8s_ver}} -p path)" \
	  {{go}} test ./... -race -count=1

# Build Go binary only
build:
	CGO_ENABLED=0 {{go}} build -o bin/k8s-auto-dash ./cmd/k8s-auto-dash

# Tidy go.mod / go.sum
tidy:
	{{go}} mod tidy

# Build image for local dev (native arch only — linux/amd64 via QEMU on Apple Silicon
# triggers Go GC/QEMU memory corruption; use image-push or CI for multi-arch builds)
image:
	docker buildx build \
	  --builder multiarch \
	  --build-arg ICONS_COMMIT={{icons_commit}} \
	  --build-arg VERSION={{tag}} \
	  -t {{image}}:{{tag}} \
	  --load \
	  .

# Build and push multi-platform image
image-push:
	docker buildx build \
	  --builder multiarch \
	  --build-arg ICONS_COMMIT={{icons_commit}} \
	  --build-arg VERSION={{tag}} \
	  -t {{image}}:{{tag}} \
	  --platform {{platforms}} \
	  --push \
	  .

# Sync generated CRD into helm chart crds/ dir
chart-sync: generate
	cp deploy/crd/k8s-auto-dash.io_dashboardconfigs.yaml \
	   deploy/helm/k8s-auto-dash/crds/dashboardconfig.yaml

# Lint helm chart
chart-lint: chart-sync
	helm lint deploy/helm/k8s-auto-dash

# Render helm chart templates
chart-template: chart-sync
	helm template test deploy/helm/k8s-auto-dash

# Generate concatenated install.yaml from helm + CRDs
manifests: chart-sync
	mkdir -p deploy/manifests
	( \
	  echo "# Generated by 'just manifests'. Do not edit by hand."; \
	  echo "# Source: deploy/helm/k8s-auto-dash"; \
	  echo "---"; \
	  cat deploy/crd/k8s-auto-dash.io_dashboardconfigs.yaml; \
	  echo "---"; \
	  helm template k8s-auto-dash deploy/helm/k8s-auto-dash \
	    --namespace k8s-auto-dash \
	    --set crd.install=false; \
	) > deploy/manifests/install.yaml
