// This file is regenerated by `make icons` from the bundled
// dashboard-icons snapshot. The placeholder list lets unit tests run
// before the icon generator runs.
export const ICON_SLUGS: readonly string[] = [
  'jellyfin', 'sonarr', 'radarr', 'prowlarr', 'plex',
  'grafana', 'prometheus', 'argocd', 'vault', 'gitea',
  'homepage', 'pihole', 'nextcloud', 'ubiquiti',
];
